export const GETQUESTIONS = 'GETQUESTIONS';
export const ADDSCORE = 'ADDSCORE';
export const SETUSER = 'SETUSER';
export const SETSTATUSLOADING = 'SETSTATUSLOADING';
export const SETQUESTIONS = 'SETQUESTIONS';
export const ADDUSER = 'ADDUSER';
export const SETQUESTIONSORDER = 'SETQUESTIONSORDER';
export const SETCURRENTQUIZNUMBER = 'SETCURRENTQUIZNUMBER'; 